[project]
name = "teraflopai"
version = "0.1.0"
description = "The official Python library for the teraflopai API"
readme = "README.md"
requires-python = ">=3.12"
authors = [
{ name = "Teraflop AI", email = "enrico@teraflop.ai" },
]
dependencies = []
